CREATE TABLE users (id TEXT PRIMARY KEY, username TEXT NOT NULL UNIQUE, name TEXT, email TEXT, enabled BOOLEAN NOT NULL, local_enabled BOOLEAN NOT NULL, password_hash TEXT, must_change_password BOOLEAN NOT NULL, language TEXT, theme TEXT);
CREATE TABLE groups (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT);
CREATE TABLE roles (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT, builtin BOOLEAN NOT NULL);
CREATE TABLE applications (id TEXT PRIMARY KEY, name TEXT, client_id TEXT NOT NULL UNIQUE, client_type TEXT, secret_hash TEXT, enabled BOOLEAN NOT NULL, icon TEXT, login_url TEXT, redirect_urls TEXT, logout_urls TEXT, origins TEXT, local_enabled BOOLEAN NOT NULL);
CREATE TABLE providers (id TEXT PRIMARY KEY, name TEXT, issuer TEXT, client_id TEXT, secret_cipher TEXT, enabled BOOLEAN NOT NULL);
CREATE TABLE permissions (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT, application_id TEXT);
CREATE TABLE user_roles (user_id TEXT REFERENCES users(id) ON DELETE RESTRICT, role_id TEXT REFERENCES roles(id) ON DELETE RESTRICT, PRIMARY KEY(user_id,role_id));
CREATE TABLE group_roles (group_id TEXT REFERENCES groups(id) ON DELETE RESTRICT, role_id TEXT REFERENCES roles(id) ON DELETE RESTRICT, PRIMARY KEY(group_id,role_id));
CREATE TABLE group_members (group_id TEXT REFERENCES groups(id) ON DELETE RESTRICT, user_id TEXT REFERENCES users(id) ON DELETE RESTRICT, PRIMARY KEY(group_id,user_id));
CREATE TABLE role_permissions (role_id TEXT REFERENCES roles(id) ON DELETE RESTRICT, permission_id TEXT REFERENCES permissions(id) ON DELETE RESTRICT, PRIMARY KEY(role_id,permission_id));
CREATE TABLE application_providers (application_id TEXT REFERENCES applications(id) ON DELETE RESTRICT, provider_id TEXT REFERENCES providers(id) ON DELETE RESTRICT, PRIMARY KEY(application_id,provider_id));
CREATE TABLE external_identities (id TEXT PRIMARY KEY, provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE RESTRICT, issuer TEXT NOT NULL, subject TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT, UNIQUE(provider_id,issuer,subject));
CREATE INDEX external_identities_user ON external_identities(user_id);
CREATE TABLE sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, credential_hash TEXT NOT NULL UNIQUE, method TEXT, provider_id TEXT, auth_time TIMESTAMP, expires_at TIMESTAMP, revoked BOOLEAN NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE INDEX sessions_user ON sessions(user_id);
CREATE TABLE auth_transactions (id TEXT PRIMARY KEY, payload TEXT, browser_hash TEXT, session_id TEXT, user_id TEXT, client_id TEXT NOT NULL REFERENCES applications(id) ON DELETE CASCADE, code_hash TEXT UNIQUE, code_expires_at TIMESTAMP, expires_at TIMESTAMP, consumed BOOLEAN NOT NULL, auth_time TIMESTAMP, method TEXT);
CREATE INDEX auth_transactions_expiry ON auth_transactions(expires_at);
CREATE TABLE upstream_transactions (id TEXT PRIMARY KEY, provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE, request_id TEXT, browser_hash TEXT, nonce TEXT, verifier TEXT, expires_at TIMESTAMP, consumed BOOLEAN NOT NULL);
CREATE INDEX upstream_transactions_expiry ON upstream_transactions(expires_at);
CREATE TABLE token_records (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, client_id TEXT NOT NULL REFERENCES applications(id) ON DELETE CASCADE, session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, scopes TEXT, expires_at TIMESTAMP, revoked BOOLEAN NOT NULL);
CREATE INDEX token_records_expiry ON token_records(expires_at);
CREATE TABLE signing_keys (id TEXT PRIMARY KEY, private_cipher TEXT, public_json TEXT, active BOOLEAN NOT NULL, created_at TIMESTAMP);
CREATE UNIQUE INDEX signing_keys_active ON signing_keys(active) WHERE active = TRUE;
CREATE TABLE events (id TEXT PRIMARY KEY, actor_id TEXT, object_id TEXT, kind TEXT, success BOOLEAN NOT NULL, request_id TEXT, created_at TIMESTAMP);
CREATE INDEX events_kind ON events(kind);
CREATE INDEX events_created ON events(created_at);

INSERT INTO roles (id,name,description,builtin) VALUES ('admin','Administrator','Built-in administrator',TRUE);
INSERT INTO permissions (id,name,description,application_id) VALUES ('dashboard:read','dashboard:read','dashboard:read','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('users:read','users:read','users:read','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('users:write','users:write','users:write','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('groups:read','groups:read','groups:read','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('groups:write','groups:write','groups:write','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('roles:read','roles:read','roles:read','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('permissions:read','permissions:read','permissions:read','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('applications:read','applications:read','applications:read','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('applications:write','applications:write','applications:write','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('providers:read','providers:read','providers:read','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('providers:write','providers:write','providers:write','');
INSERT INTO permissions (id,name,description,application_id) VALUES ('authorization:write','authorization:write','Manage ordinary roles and assignments','');
